apiVersion: v1 
kind: Service 
metadata:
  name: vpromq01 ##confirm this from application.properties
spec:
  ports:
    - port: 15672
      targetPort: vpromq-port
      protocol: TCP
  selector:
    app: vpromq
  type: ClusterIP