apiVersion: v1 
kind: Service 
metadata:
  name: vprodb ##confirm this from application.properties
spec:
  ports:
    - port: 3306
      targetPort: vprodb-port
      protocol: TCP
  selector:
    app: vprodb
  type: ClusterIP